Repository CS2103-AY1819S1-W10-4/main, pull requests merged in 2018-11, with the labels that each got.

#172 Updated documentation
  docs/DeveloperGuide.adoc
  docs/team/benntay.adoc
Labels: Ready to Review

#171 Docs/Documentation Clean Up
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/java/seedu/souschef/MainApp.java
Labels: Ready to Review, lifecycle.Testing

#170 Docs/IM Update docs, Adjust implementations
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/commands/CrossFindCommand.java
  src/main/java/seedu/souschef/logic/commands/ListCommand.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/CrossFindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/FindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/SelectCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/CrossParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/IngredientParser.java
  src/main/java/seedu/souschef/ui/DetailPanel.java
Labels: Ready to Review

#183 Docs/IM add universal command -cross
  docs/UserGuide.adoc
Labels: Ready to Review

#211 Documentation/benntay
  docs/UserGuide.adoc
Labels: Ready to Review

#184 Feature/IM : adjust precidate, update list command
  src/main/java/seedu/souschef/logic/commands/ListCommand.java
  src/main/java/seedu/souschef/logic/parser/commandparser/CrossFindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/model/Model.java
Labels: Ready to Review

#218 Feature/IM Fix date related bug
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
  src/main/java/seedu/souschef/storage/ingredient/XmlAdaptedIngredient.java
Labels: Ready to Review

#219 Feature/mealplanner exceptions and messages update
  src/main/java/seedu/souschef/logic/commands/PlanMealCommand.java
  src/main/java/seedu/souschef/logic/commands/SelectCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/Context.java
  src/main/java/seedu/souschef/logic/parser/commandparser/SelectCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/UniversalParser.java
  src/main/java/seedu/souschef/model/planner/Day.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
  src/main/java/seedu/souschef/storage/StorageManager.java
Labels: Ready to Review

#213 Bug patch and improve code quality
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/commands/ShowHealthPlanDetailsCommand.java
  src/main/java/seedu/souschef/logic/parser/ParserUtil.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddMealHealthPlanCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteMealHealthPlanCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/ShowHealthPlanDetailsCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/HealthPlanParser.java
  src/main/java/seedu/souschef/model/healthplan/CurrentWeight.java
  src/main/java/seedu/souschef/model/healthplan/TargetWeight.java
  src/main/java/seedu/souschef/ui/HealthPlanDetailsPanel.java
  src/main/java/seedu/souschef/ui/MainWindow.java
  src/main/resources/view/HealthPlanDetailsPanel.fxml
Labels: Ready to Review

#223 Removal of "PT" from CookTime
  data/mealplan.xml
  data/recipe.xml
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/RecipeBuilderCommandParser.java
  src/main/java/seedu/souschef/model/recipe/CookTime.java
  src/main/java/seedu/souschef/model/recipe/Instruction.java
  src/main/java/seedu/souschef/storage/recipe/XmlAdaptedInstruction.java
  src/main/java/seedu/souschef/ui/FavouritesCard.java
  src/main/java/seedu/souschef/ui/RecipeCard.java
  src/test/data/XmlSerializableAddressBookTest/duplicateRecipeAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalRecipesAddressBook.xml
  src/test/data/XmlUtilTest/invalidRecipeField.xml
  src/test/data/XmlUtilTest/missingRecipeField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validRecipe.xml
  src/test/java/seedu/souschef/commons/util/XmlUtilTest.java
  src/test/java/seedu/souschef/logic/commands/CommandTestUtil.java
  src/test/java/seedu/souschef/logic/parser/CommandParserUtilTest.java
  src/test/java/seedu/souschef/model/AddressBookTest.java
  src/test/java/seedu/souschef/model/ModelManagerTest.java
  src/test/java/seedu/souschef/model/VersionedAppContentTest.java
  src/test/java/seedu/souschef/model/recipe/CookTimeTest.java
  src/test/java/seedu/souschef/model/recipe/RecipeTest.java
  src/test/java/seedu/souschef/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/souschef/storage/XmlAdaptedRecipeTest.java
  src/test/java/seedu/souschef/storage/XmlAddressBookStorageTest.java
  src/test/java/seedu/souschef/testutil/RecipeBuilder.java
  src/test/java/seedu/souschef/testutil/TypicalRecipes.java
  src/test/java/seedu/souschef/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: Ready to Review

#225 SampleData Update
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
Labels: Ready to Review

#234 Feature/mealplanner: Implement find and list commands
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/parser/commandparser/FindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
  src/main/java/seedu/souschef/model/planner/MealPlanContainsDatePredicate.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
Labels: Ready to Review, lifecycle.Implementation

#232 Messages and string formating
  data/recipe.xml
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/commons/util/StringUtil.java
  src/main/java/seedu/souschef/model/recipe/Name.java
Labels: Ready to Review

#228 Fixed noted bugs
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/model/healthplan/CurrentWeight.java
  src/main/java/seedu/souschef/model/healthplan/TargetWeight.java
Labels: Ready to Review

#236 V1.4 Documentations
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/recipe_add_add.png
  docs/images/recipe_add_cont.png
  docs/images/recipe_add_end.png
  docs/images/recipe_search_seq.png
  docs/team/junrong09.adoc
  src/main/java/seedu/souschef/logic/History.java
  src/main/java/seedu/souschef/logic/commands/BuildRecipeInstructionCommand.java
Labels: Ready to Review

#220 Documentation update
  docs/team/alecngzw.adoc
  docs/team/barkhyehyeon.adoc
  docs/team/benntay.adoc
  docs/team/junrong09.adoc
  docs/team/limshiminjonathan.adoc
Labels: Ready to Review

#238 Documentation updates
  docs/DeveloperGuide.adoc
  docs/team/alecngzw.adoc
  src/main/java/seedu/souschef/model/healthplan/TargetWeight.java
Labels: Ready to Review

#239 Docs/IM Update dev guide
  docs/DeveloperGuide.adoc
  docs/team/barkhyehyeon.adoc
  src/main/java/seedu/souschef/logic/parser/commandparser/FindCommandParser.java
  src/main/java/seedu/souschef/model/ingredient/IngredientNameContainsKeywordsPredicate.java
Labels: Ready to Review

#241 Documentation/benntay
  docs/team/benntay.adoc
Labels: Ready to Review

#242 Cleanup/mealplanner
  docs/DeveloperGuide.adoc
  docs/images/MealPlannerClassDiagram.png
  docs/images/UiPanelNewHierarchy.png
  docs/images/UiPanelOldHierarchy.png
  src/main/java/seedu/souschef/logic/commands/PlanMealCommand.java
  src/main/java/seedu/souschef/logic/commands/SelectCommand.java
  src/main/java/seedu/souschef/model/planner/Breakfast.java
  src/main/java/seedu/souschef/model/planner/Day.java
  src/main/java/seedu/souschef/model/planner/Dinner.java
  src/main/java/seedu/souschef/model/planner/Lunch.java
  src/main/java/seedu/souschef/model/planner/Meal.java
  src/main/java/seedu/souschef/model/planner/exceptions/DayNotFoundException.java
  src/main/java/seedu/souschef/model/planner/exceptions/MealRecipeNotFoundException.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
  src/main/java/seedu/souschef/storage/mealplanner/XmlAdaptedMealPlan.java
  src/main/java/seedu/souschef/ui/HealthPlanDetailsPanel.java
  src/main/java/seedu/souschef/ui/MealPlanCard.java
Labels: Ready to Review, lifecycle.Implementation

#243 Cleanup/ui
  docs/DeveloperGuide.adoc
  src/main/java/seedu/souschef/MainApp.java
  src/main/java/seedu/souschef/commons/events/ui/ListPanelSwitchEvent.java
  src/main/java/seedu/souschef/logic/Logic.java
  src/main/java/seedu/souschef/logic/LogicManager.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/PlanMealCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/SelectCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/UniversalParser.java
  src/main/java/seedu/souschef/model/planner/Meal.java
  src/main/java/seedu/souschef/ui/MainWindow.java
  src/main/java/seedu/souschef/ui/Ui.java
  src/main/java/seedu/souschef/ui/UiManager.java
Labels: Ready to Review, lifecycle.Implementation

#212 Fix indexing bug for favourites
  src/main/java/seedu/souschef/logic/commands/AddFavouriteCommand.java
Labels: type.Bug

#244 Feature/recipe commands
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/commands/EditCommand.java
  src/main/java/seedu/souschef/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/RecipeBuilderCommandParser.java
Labels: Ready to Review

#240 DeveloperGuide.adoc: Update code snippet file directory.
  docs/DeveloperGuide.adoc
  docs/team/junrong09.adoc
Labels: Ready to Review

#247 Test Cases: HealthPlan and cleaning up code and regex switch
  src/main/java/seedu/souschef/model/healthplan/Age.java
  src/main/java/seedu/souschef/model/healthplan/CurrentHeight.java
  src/main/java/seedu/souschef/model/healthplan/Duration.java
  src/main/java/seedu/souschef/model/healthplan/Scheme.java
  src/test/java/seedu/souschef/model/healthplan/AgeTest.java
  src/test/java/seedu/souschef/model/healthplan/CurrentHeightTest.java
  src/test/java/seedu/souschef/model/healthplan/CurrentWeightTest.java
  src/test/java/seedu/souschef/model/healthplan/DurationTest.java
  src/test/java/seedu/souschef/model/healthplan/HealthPlanNameTest.java
  src/test/java/seedu/souschef/model/healthplan/HealthPlanTest.java
  src/test/java/seedu/souschef/model/healthplan/TargetWeightTest.java
  src/test/java/seedu/souschef/testutil/HealthPlanBuilder.java
Labels: Ready to Review

#248 Documentation: added tags, revised some text
  docs/UserGuide.adoc
  docs/team/alecngzw.adoc
Labels: Ready to Review

#249 Docs/IM
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/IngredientModelDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/LogicSequenceDiagram.png
  docs/team/barkhyehyeon.adoc
  src/main/java/seedu/souschef/model/ingredient/Ingredient.java
  src/main/java/seedu/souschef/model/ingredient/IngredientPortion.java
Labels: Ready to Review

#251 Clean up/IM more clean ups
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/logic/commands/CrossFindCommand.java
  src/main/java/seedu/souschef/logic/parser/commandparser/CrossFindCommandParser.java
  src/main/java/seedu/souschef/model/ingredient/IngredientServingUnit.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
Labels: Ready to Review

#252 SampleDataUtil.java: Add sample recipes
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
Labels: Ready to Review

#253 Sample Data Utils: add recipes
  data/healthplan.xml
  data/recipe.xml
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
Labels: Ready to Review

#181 Implemented Surprise Command for Recipe Context
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/commands/SurpriseCommand.java
  src/main/java/seedu/souschef/logic/parser/contextparser/RecipeParser.java
Labels: Ready to Review, lifecycle.Implementation, priority.Medium

#256 Deletion across multiple models and clean up
  docs/DeveloperGuide.adoc
  docs/images/UiClassDiagram.png
  docs/team/benntay.adoc
  src/main/java/seedu/souschef/MainApp.java
  src/main/java/seedu/souschef/commons/events/model/MealPlanDeletedEvent.java
  src/main/java/seedu/souschef/commons/events/model/RecipeDeletedEvent.java
  src/main/java/seedu/souschef/commons/events/storage/SwitchFeatureStorageEvent.java
  src/main/java/seedu/souschef/logic/LogicManager.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
  src/main/java/seedu/souschef/model/Model.java
  src/main/java/seedu/souschef/model/ModelManager.java
  src/main/java/seedu/souschef/model/ModelSet.java
  src/main/java/seedu/souschef/model/ModelSetCoordinator.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
  src/main/java/seedu/souschef/storage/Storage.java
  src/main/java/seedu/souschef/storage/StorageManager.java
Labels: Ready to Review, lifecycle.Implementation

#258 Docs/v1.4 finalisation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/recipe_add_add.png
  docs/images/recipe_add_cont.png
  docs/images/recipe_add_end.png
  docs/images/recipe_class_diagram.png
  docs/images/recipe_search_seq.png
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
Labels: Ready to Review

#257 Cleanup/code quality
  src/main/java/seedu/souschef/MainApp.java
  src/main/java/seedu/souschef/logic/parser/ParserUtil.java
  src/main/java/seedu/souschef/logic/parser/contextparser/RecipeParser.java
  src/main/java/seedu/souschef/model/AppContent.java
  src/main/java/seedu/souschef/model/ReadOnlyAppContent.java
  src/main/resources/images/address_book_32.png
  src/test/data/XmlAddressBookStorageTest/invalidAndValidRecipeAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidRecipeAddressBook.xml
  src/test/data/XmlRecipeStorageTest/NotXmlFormatRecipe.xml
  src/test/data/XmlRecipeStorageTest/invalidAndValidRecipe.xml
  src/test/data/XmlRecipeStorageTest/invalidRecipe.xml
  src/test/java/seedu/souschef/logic/commands/CommandTestUtil.java
  src/test/java/seedu/souschef/logic/commands/EditCommandTest.java
  src/test/java/seedu/souschef/logic/commands/EditRecipeDescriptorTest.java
  src/test/java/seedu/souschef/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/souschef/model/AppContentTest.java
  src/test/java/seedu/souschef/model/RecipeModelManagerTest.java
  src/test/java/seedu/souschef/model/VersionedAppContentTest.java
  src/test/java/seedu/souschef/model/recipe/CookTimeTest.java
  src/test/java/seedu/souschef/model/recipe/DifficultyTest.java
  src/test/java/seedu/souschef/model/recipe/NameTest.java
  src/test/java/seedu/souschef/model/recipe/RecipeContainsKeywordsPredicateTest.java
  src/test/java/seedu/souschef/model/recipe/RecipeTest.java
  src/test/java/seedu/souschef/model/recipe/TagTest.java
  src/test/java/seedu/souschef/model/recipe/UniqueRecipeListTest.java
  src/test/java/seedu/souschef/model/tag/TagTest.java
  src/test/java/seedu/souschef/storage/StorageManagerTest.java
  src/test/java/seedu/souschef/storage/XmlAdaptedRecipeTest.java
  src/test/java/seedu/souschef/storage/XmlRecipeStorageTest.java
  src/test/java/seedu/souschef/storage/XmlSerializableRecipeTest.java
  src/test/java/seedu/souschef/testutil/IngredientsBuilder.java
  src/test/java/seedu/souschef/testutil/InstructionBuilder.java
  src/test/java/seedu/souschef/testutil/RecipeBuilder.java
  src/test/java/seedu/souschef/testutil/TypicalRecipes.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: Ready to Review

#259 Update dev guide[final]
  docs/DeveloperGuide.adoc
Labels: Ready to Review

#263 Update user guide and developer guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Ready to Review

#262 Feature/IM fix coding style
  src/main/java/seedu/souschef/logic/commands/CrossFindCommand.java
  src/main/java/seedu/souschef/logic/parser/commandparser/CrossFindCommandParser.java
  src/test/java/seedu/souschef/logic/parser/AddCommandParserTest.java
Labels: Ready to Review

#267 Fixed bug for missing prefix
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
Labels: Ready to Review

#265 Finalcleanup/benntay
  docs/team/benntay.adoc
  src/main/java/seedu/souschef/commons/events/model/MealPlannerClearedEvent.java
  src/main/java/seedu/souschef/logic/commands/ClearMealPlannerCommand.java
  src/main/java/seedu/souschef/logic/commands/DeleteCommand.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
  src/main/java/seedu/souschef/model/ModelSetCoordinator.java
  src/main/java/seedu/souschef/model/planner/Day.java
Labels: Ready to Review, priority.High

#269 Documentation: fix some errors on text and added diagram for dev guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/StorageClassDiagramRevamp.png
  docs/images/healthPlanClassDiagram.png
Labels: Ready to Review

#268 Cleanup and documents
  docs/DeveloperGuide.adoc
  docs/team/junrong09.adoc
  src/test/java/seedu/souschef/logic/commands/CommandTestUtil.java
  src/test/java/seedu/souschef/logic/commands/RedoCommandTest.java
  src/test/java/seedu/souschef/logic/commands/UndoCommandTest.java
Labels: Ready to Review

#270 Finalcleanup/benntay
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/StorageClassDiagramRevamp.png
  docs/images/healthPlanClassDiagram.png
  docs/team/benntay.adoc
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/commons/events/model/RecipeEditedEvent.java
  src/main/java/seedu/souschef/logic/commands/EditCommand.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/CrossFindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/model/ModelSetCoordinator.java
  src/main/java/seedu/souschef/model/ingredient/Ingredient.java
  src/main/java/seedu/souschef/storage/mealplanner/XmlAdaptedMealPlan.java
  src/test/java/seedu/souschef/logic/commands/SelectCommandTest.java
  src/test/java/seedu/souschef/model/ingredient/IngredientTest.java
Labels: Ready to Review, priority.High

#273 Documentations: healthplan updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/StorageClassDiagramRevamp.png
  docs/images/healthPlanClassDiagram.png
Labels: Ready to Review

#277 update message prompts to be clearer
  src/main/java/seedu/souschef/model/healthplan/Age.java
  src/main/java/seedu/souschef/model/healthplan/CurrentHeight.java
  src/main/java/seedu/souschef/model/healthplan/Duration.java
Labels: Ready to Review

#276 Finalbugfixes/mealplanner
  src/main/java/seedu/souschef/logic/parser/commandparser/PlanMealCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/SelectCommandParser.java
Labels: Ready to Review
