Repository CS2103-AY1819S1-W10-4/main, pull requests merged in 2018-10, with the labels that each got.

#39 Docs change
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
Labels: Ready to Review

#43 Revert "Added Surprise Command"
  src/main/java/seedu/address/logic/commands/SurpriseCommand.java
  src/main/java/seedu/address/logic/parser/AppContentParser.java
Labels: Ready to Review

#57 RepoSense Author Specification
  _reposense/config.json
Labels: Ready to Review

#64 Restructure Logic
  src/main/java/seedu/souschef/MainApp.java
  src/main/java/seedu/souschef/logic/CommandHistory.java
  src/main/java/seedu/souschef/logic/EditRecipeDescriptor.java
  src/main/java/seedu/souschef/logic/LogicManager.java
  src/main/java/seedu/souschef/logic/commands/AddCommand.java
  src/main/java/seedu/souschef/logic/commands/ClearCommand.java
  src/main/java/seedu/souschef/logic/commands/Command.java
  src/main/java/seedu/souschef/logic/commands/DeleteCommand.java
  src/main/java/seedu/souschef/logic/commands/EditCommand.java
  src/main/java/seedu/souschef/logic/commands/ExitCommand.java
  src/main/java/seedu/souschef/logic/commands/FindCommand.java
  src/main/java/seedu/souschef/logic/commands/HelpCommand.java
  src/main/java/seedu/souschef/logic/commands/HistoryCommand.java
  src/main/java/seedu/souschef/logic/commands/ListCommand.java
  src/main/java/seedu/souschef/logic/commands/RedoCommand.java
  src/main/java/seedu/souschef/logic/commands/SelectCommand.java
  src/main/java/seedu/souschef/logic/commands/SurpriseCommand.java
  src/main/java/seedu/souschef/logic/commands/UndoCommand.java
  src/main/java/seedu/souschef/logic/parser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/CommandParser.java
  src/main/java/seedu/souschef/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/souschef/logic/parser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/FindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/RecipeParser.java
  src/main/java/seedu/souschef/logic/parser/SelectCommandParser.java
  src/test/java/seedu/souschef/logic/LogicManagerTest.java
  src/test/java/seedu/souschef/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/souschef/logic/commands/ClearCommandTest.java
  src/test/java/seedu/souschef/logic/commands/CommandTestUtil.java
  src/test/java/seedu/souschef/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/souschef/logic/commands/EditCommandTest.java
  src/test/java/seedu/souschef/logic/commands/EditRecipeDescriptorTest.java
  src/test/java/seedu/souschef/logic/commands/ExitCommandTest.java
  src/test/java/seedu/souschef/logic/commands/FindCommandTest.java
  src/test/java/seedu/souschef/logic/commands/ListCommandTest.java
  src/test/java/seedu/souschef/logic/commands/RedoCommandTest.java
  src/test/java/seedu/souschef/logic/commands/SelectCommandTest.java
  src/test/java/seedu/souschef/logic/commands/UndoCommandTest.java
  src/test/java/seedu/souschef/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/AppContentParserTest.java
  src/test/java/seedu/souschef/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/souschef/logic/parser/CommandParserUtilTest.java
  src/test/java/seedu/souschef/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/SelectCommandParserTest.java
  src/test/java/seedu/souschef/testutil/EditRecipeDescriptorBuilder.java
  src/test/java/seedu/souschef/testutil/RecipeUtil.java
  src/test/java/seedu/souschef/ui/CommandBoxTest.java
  src/test/java/seedu/souschef/ui/MainWindowCloseTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: Ready to Review

#65 UI revamp
  src/main/java/seedu/souschef/commons/events/ui/GenericPanelSelectionChangedEvent.java
  src/main/java/seedu/souschef/commons/events/ui/RecipePanelSelectionChangedEvent.java
  src/main/java/seedu/souschef/model/planner/Meal.java
  src/main/java/seedu/souschef/ui/GenericCard.java
  src/main/java/seedu/souschef/ui/GenericListPanel.java
  src/main/java/seedu/souschef/ui/MainWindow.java
  src/main/java/seedu/souschef/ui/RecipeCard.java
  src/main/java/seedu/souschef/ui/RecipeListPanel.java
  src/main/java/seedu/souschef/ui/Ui.java
  src/main/java/seedu/souschef/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecipeListPanel.fxml
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: Ready to Review, lifecycle.Design, priority.High

#66 Implement some universal commands in logic
  src/main/java/seedu/souschef/logic/commands/ContextCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/UniversalParser.java
  src/test/java/seedu/souschef/logic/LogicManagerTest.java
Labels: Ready to Review

#68 Add Folders to logic
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/commandParser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandParser/CommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandParser/DeleteCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandParser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandParser/FindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandParser/SelectCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextParser/RecipeParser.java
  src/main/java/seedu/souschef/logic/parser/contextParser/UniversalParser.java
  src/main/java/seedu/souschef/storage/FeatureStorage.java
  src/main/java/seedu/souschef/storage/StorageManager.java
  src/main/java/seedu/souschef/storage/recipe/XmlRecipeStorage.java
  src/main/java/seedu/souschef/storage/recipe/XmlSerializableAddressBook.java
  src/test/java/seedu/souschef/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/souschef/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/souschef/logic/parser/SelectCommandParserTest.java
Labels: Ready to Review, lifecycle.Design

#73 Make success messages for 5 shared command classes as generic
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/CommandHistory.java
  src/main/java/seedu/souschef/logic/commands/AddCommand.java
  src/main/java/seedu/souschef/logic/commands/DeleteCommand.java
  src/main/java/seedu/souschef/logic/commands/EditCommand.java
  src/main/java/seedu/souschef/logic/commands/FindCommand.java
  src/main/java/seedu/souschef/logic/commands/ListCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/test/java/seedu/souschef/logic/LogicManagerTest.java
  src/test/java/seedu/souschef/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/souschef/logic/commands/FindCommandTest.java
  src/test/java/seedu/souschef/logic/commands/ListCommandTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: Ready to Review

#76 Implement Add, Delete command for ingredient in logic
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/commands/AddCommand.java
  src/main/java/seedu/souschef/logic/commands/DeleteCommand.java
  src/main/java/seedu/souschef/logic/commands/EditCommand.java
  src/main/java/seedu/souschef/logic/commands/FindCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/CommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/FindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/SelectCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/IngredientParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/UniversalParser.java
  src/main/java/seedu/souschef/model/ModelSet.java
  src/main/java/seedu/souschef/model/ingredient/Ingredient.java
  src/test/java/seedu/souschef/logic/parser/DeleteCommandParserTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: Ready to Review

#82 Recipe commands
  data/recipe.xml
  src/main/java/seedu/souschef/logic/parser/CliSyntax.java
  src/main/java/seedu/souschef/model/UserPrefs.java
  src/main/java/seedu/souschef/model/recipe/Address.java
  src/main/java/seedu/souschef/model/recipe/NameContainsKeywordsPredicate.java
  src/main/java/seedu/souschef/storage/StorageManager.java
  src/main/java/seedu/souschef/ui/MainWindow.java
  src/test/java/seedu/souschef/TestApp.java
  src/test/java/seedu/souschef/model/ModelManagerTest.java
  src/test/java/seedu/souschef/model/recipe/AddressTest.java
  src/test/java/seedu/souschef/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, status.Ongoing

#92 Change test json label and value
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/souschef/model/recipe/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/souschef/storage/JsonUserPrefsStorageTest.java
Labels: Ready to Review

#91 Ingredient model restructuring
  docs/team/barkhyehyeon.adoc
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteCommandParser.java
  src/main/java/seedu/souschef/model/ingredient/Ingredient.java
  src/main/java/seedu/souschef/model/ingredient/IngredientAmount.java
  src/main/java/seedu/souschef/model/ingredient/IngredientDate.java
  src/main/java/seedu/souschef/model/ingredient/IngredientDefinition.java
  src/main/java/seedu/souschef/model/ingredient/IngredientName.java
  src/main/java/seedu/souschef/model/ingredient/IngredientPortion.java
  src/main/java/seedu/souschef/model/ingredient/IngredientServingUnit.java
  src/main/java/seedu/souschef/model/ingredient/Inventory.java
  src/main/java/seedu/souschef/model/ingredient/UniqueIngredient.java
  src/main/java/seedu/souschef/model/ingredient/UniqueIngredientList.java
  src/main/java/seedu/souschef/storage/ingredient/XmlAdaptedIngredient.java
  src/main/java/seedu/souschef/ui/IngredientCard.java
Labels: Ready to Review

#95 Fix ingredient storage implementation
  data/ingredient.xml
  src/main/java/seedu/souschef/model/AppContent.java
  src/main/java/seedu/souschef/storage/ingredient/XmlSerializableIngredient.java
Labels: Ready to Review

#102 Documentation updates
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/MealPlannerClassDiagram.png
  docs/team/benntay.adoc
Labels: Ready to Review

#59 Portfolio/UserGuide/DeveloperGuide Update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/junrong09.adoc
Labels: Ready to Review, lifecycle.Requirement

#101 Update messages for ingredient add/ delete command
  docs/DeveloperGuide.adoc
  src/main/java/seedu/souschef/commons/core/Messages.java
Labels: Ready to Review

#103 Add logic sequence diagram
  docs/DeveloperGuide.adoc
  docs/images/LogicSequenceDiagram.png
Labels: Ready to Review

#104 Documentation update
  docs/DeveloperGuide.adoc
Labels: Ready to Review

#120 Docs/im : Update docs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/LogicClassDiagram.png
Labels: Ready to Review

#110 Documentation & reposense
  _reposense/config.json
Labels: Ready to Review

#129 Documentation/benntay
  docs/DeveloperGuide.adoc
  docs/images/UiPanelNewHierarchy.png
  docs/images/UiPanelOldHierarchy.png
Labels: Ready to Review

#132 Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: Ready to Review, lifecycle.Requirement

#133 MainApp.java: Update release version
  src/main/java/seedu/souschef/MainApp.java
Labels: Ready to Review

#113 Feature/IM: develop edit, find command for IM
  src/main/java/seedu/souschef/logic/commands/FindCommand.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/FindCommandParser.java
  src/main/java/seedu/souschef/model/ingredient/IngredientName.java
  src/main/java/seedu/souschef/model/recipe/IngredientNameContainsKeywordsPredicate.java
Labels: Ready to Review, lifecycle.Implementation

#130 Feature/mealplanner
  data/mealplan.xml
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/commands/ClearMealPlannerCommand.java
  src/main/java/seedu/souschef/logic/commands/DeleteCommand.java
  src/main/java/seedu/souschef/logic/commands/DisplayMealPlannerCommand.java
  src/main/java/seedu/souschef/logic/commands/PlanMealCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/PlanMealCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/RecipeParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/UniversalParser.java
  src/main/java/seedu/souschef/model/AppContent.java
  src/main/java/seedu/souschef/model/Model.java
  src/main/java/seedu/souschef/model/ModelManager.java
  src/main/java/seedu/souschef/model/UniqueList.java
  src/main/java/seedu/souschef/model/UserPrefs.java
  src/main/java/seedu/souschef/model/planner/Day.java
  src/main/java/seedu/souschef/model/planner/DayComparator.java
  src/main/java/seedu/souschef/model/planner/Meal.java
  src/main/java/seedu/souschef/storage/StorageManager.java
  src/main/java/seedu/souschef/storage/XmlFileStorage.java
  src/main/java/seedu/souschef/storage/mealplanner/XmlAdaptedMealPlan.java
  src/main/java/seedu/souschef/storage/mealplanner/XmlMealPlanStorage.java
  src/main/java/seedu/souschef/storage/mealplanner/XmlSerializableMealPlan.java
  src/main/java/seedu/souschef/storage/recipe/XmlAdaptedLiteRecipe.java
  src/main/java/seedu/souschef/ui/MealPlanCard.java
Labels: Ready to Review, lifecycle.Implementation

#140 Feature/Cross context parsing
  src/main/java/seedu/souschef/logic/CommandHistory.java
  src/main/java/seedu/souschef/logic/commands/AddCommand.java
  src/main/java/seedu/souschef/logic/commands/AddFavouriteCommand.java
  src/main/java/seedu/souschef/logic/commands/ContextCommand.java
  src/main/java/seedu/souschef/logic/commands/DeleteCommand.java
  src/main/java/seedu/souschef/logic/commands/EditCommand.java
  src/main/java/seedu/souschef/logic/commands/FindCommand.java
  src/main/java/seedu/souschef/logic/commands/ListCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/CliSyntax.java
  src/main/java/seedu/souschef/logic/parser/Context.java
  src/main/java/seedu/souschef/logic/parser/contextparser/FavouritesParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/HealthPlanParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/IngredientParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/RecipeParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/UniversalParser.java
  src/main/java/seedu/souschef/storage/Storage.java
  src/main/java/seedu/souschef/storage/StorageManager.java
Labels: Ready to Review, lifecycle.Design, lifecycle.Implementation

#136 Feature/recipe instructions
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/logic/commands/SelectCommand.java
  src/main/java/seedu/souschef/logic/parser/contextparser/RecipeParser.java
  src/main/java/seedu/souschef/model/ingredient/IngredientAmount.java
  src/main/java/seedu/souschef/model/ingredient/IngredientDefinition.java
  src/main/java/seedu/souschef/model/ingredient/IngredientName.java
  src/main/java/seedu/souschef/model/recipe/NameContainsKeywordsPredicate.java
  src/main/java/seedu/souschef/model/recipe/Recipe.java
  src/main/java/seedu/souschef/ui/DetailPanel.java
  src/main/java/seedu/souschef/ui/MainWindow.java
  src/main/java/seedu/souschef/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailPanel.fxml
Labels: lifecycle.Implementation, priority.High, status.Ongoing

#137 Feature/mealplanner storage bug fix
  src/main/java/seedu/souschef/logic/commands/DeleteCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/RecipeParser.java
Labels: Ready to Review

#138 Feature/IM : implement inventory command
  src/main/java/seedu/souschef/logic/InventoryComparator.java
  src/main/java/seedu/souschef/logic/InventoryPredicate.java
  src/main/java/seedu/souschef/logic/commands/InventoryCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/IngredientParser.java
  src/main/java/seedu/souschef/model/ingredient/Ingredient.java
  src/main/java/seedu/souschef/model/ingredient/IngredientAmount.java
  src/main/java/seedu/souschef/model/ingredient/IngredientDate.java
  src/main/java/seedu/souschef/model/ingredient/IngredientDefinition.java
  src/main/java/seedu/souschef/model/ingredient/IngredientName.java
  src/main/java/seedu/souschef/model/ingredient/IngredientPortion.java
  src/main/java/seedu/souschef/model/ingredient/IngredientServingUnit.java
  src/main/java/seedu/souschef/model/ingredient/ServingUnit.java
  src/main/java/seedu/souschef/model/recipe/NameContainsKeywordsPredicate.java
  src/main/java/seedu/souschef/model/recipe/Recipe.java
  src/main/java/seedu/souschef/storage/ingredient/XmlAdaptedIngredient.java
  src/main/java/seedu/souschef/storage/ingredient/XmlAdaptedIngredientPortion.java
Labels: Ready to Review

#148 feature/mealplanner: Select Command
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/logic/parser/commandparser/SelectCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/MealPlannerParser.java
Labels: Ready to Review

#141 Update user guide/ dev guide(based on review) for IM
  docs/UserGuide.adoc
  docs/images/LogicClassDiagram.png
  docs/images/LogicSequenceDiagram.png
Labels: Ready to Review

#150 Feature/recipe instructions (Edit command)
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/commons/core/Messages.java
  src/main/java/seedu/souschef/logic/EditRecipeDescriptor.java
  src/main/java/seedu/souschef/logic/commands/EditCommand.java
  src/main/java/seedu/souschef/logic/parser/CliSyntax.java
  src/main/java/seedu/souschef/logic/parser/ParserUtil.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
Labels: lifecycle.Implementation, priority.High, status.Ongoing

#152 Update user guide
  docs/UserGuide.adoc
Labels: Ready to Review

#139 HealthPlan add and display Meal Plan enhancement
  src/main/java/seedu/souschef/commons/events/ui/BrowserUiChangedEvent.java
  src/main/java/seedu/souschef/logic/commands/AddMealHealthPlanCommand.java
  src/main/java/seedu/souschef/logic/commands/DeleteMealHealthPlanCommand.java
  src/main/java/seedu/souschef/logic/commands/DisplayMealPlanCommand.java
  src/main/java/seedu/souschef/logic/commands/ShowHealthPlanDetailsCommand.java
  src/main/java/seedu/souschef/logic/parser/AppContentParser.java
  src/main/java/seedu/souschef/logic/parser/CliSyntax.java
  src/main/java/seedu/souschef/logic/parser/ParserUtil.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddMealHealthPlanCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/DeleteMealHealthPlanCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/HealthPlanParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/UniversalParser.java
  src/main/java/seedu/souschef/model/healthplan/HealthPlan.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
  src/main/java/seedu/souschef/storage/healthplan/XmlAdaptedHealthPlan.java
  src/main/java/seedu/souschef/ui/HealthPlanDetailsPanel.java
  src/main/java/seedu/souschef/ui/MainWindow.java
  src/main/java/seedu/souschef/ui/Ui.java
  src/main/java/seedu/souschef/ui/UiManager.java
  src/main/resources/view/HealthPlanDetailsPanel.fxml
Labels: Ready to Review

#160 Feature/IM adjust ingredient related classes
  src/main/java/seedu/souschef/logic/IngredientDateComparator.java
  src/main/java/seedu/souschef/logic/parser/ParserUtil.java
  src/main/java/seedu/souschef/logic/parser/commandparser/AddCommandParser.java
  src/main/java/seedu/souschef/logic/parser/commandparser/EditCommandParser.java
  src/main/java/seedu/souschef/model/ingredient/IngredientAmount.java
  src/main/java/seedu/souschef/model/ingredient/IngredientDate.java
  src/main/java/seedu/souschef/model/ingredient/IngredientDefinition.java
  src/main/java/seedu/souschef/model/ingredient/IngredientPortion.java
  src/main/java/seedu/souschef/model/util/SampleDataUtil.java
  src/main/java/seedu/souschef/storage/ingredient/XmlAdaptedIngredient.java
  src/main/java/seedu/souschef/storage/ingredient/XmlAdaptedIngredientPortion.java
Labels: Ready to Review

#165 Update user guide + adjust list command
  docs/UserGuide.adoc
  src/main/java/seedu/souschef/logic/parser/commandparser/CrossFindCommandParser.java
  src/main/java/seedu/souschef/logic/parser/contextparser/CrossParser.java
Labels: Ready to Review
